tugas_4/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});
Route::resource('employee', 'Employees');
Route::get('employee-export','Employees@export');
Route::get('employee-exportPDF','Employees@exportPDF');
// 
Route::get('company-export','CompanyController@export');
Route::resource('company', 'CompanyController');
Route::get('company-exportPDF','CompanyController@exportPDF');

tugas_4/app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    //
}

tugas_4/app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    //
}

tugas_4/app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

tugas_4/app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Company;
use Illuminate\Http\Request;
use App\Exports\CompanyExport;
use Maatwebsite\Excel\Facades\Excel;
use PDF;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies = Company::all();
        return view('company.index',compact('companies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('company.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $employee = new Company;
        $employee->nama = $request->nama;
        $employee->alamat = $request->alamat;
        $employee->save();
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $company  = Company::find($id);
        return view('company.edit', compact(['company']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $company = Company::find($id);
        $company->nama = $request->nama;
        $company->alamat = $request->alamat;
        $company->update();
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $company = Company::find($id);
        $company->delete();
        return back();
    }
    public function export() 
    {
        return Excel::download(new CompanyExport,'Company.xlsx');
    }
    public function exportPDF()
    {
        $companies = Company::all();
        $pdf = PDF::loadView('pdf.companies', ['companies' => $companies]);
        return $pdf->download('companies.pdf');
    }
}

tugas_4/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

tugas_4/app/Http/Controllers/Employees.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Employee;
use App\Company;
use App\Exports\EmployeeExport;
use Maatwebsite\Excel\Facades\Excel;
use PDF;

class Employees extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        $employees = Employee::all();
        $employeest = Employee::all();
        $companies = Company::all();

        return view('employees.index', compact('employees','companies','employeest'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {   
        $employees = Employee::all();
        $companies = Company::all();
        return view('employees.create', compact('companies','employees'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $employee = new Employee;
        $employee->nama = $request->nama;
        $employee->atasan_id = $request->atasan_id;
        $employee->company_id = $request->company_id;
        $employee->save();
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $employees = Employee::all();
        $employee = Employee::find($id);
        $companies  = Company::all();
        return view('employees.edit', compact(['employee', 'companies','employees']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $employee = Employee::find($id);
        $employee->nama = $request->nama;
        $employee->atasan_id = $request->atasan_id;
        $employee->company_id = $request->company_id;
        $employee->save();
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $employee = Employee::find($id);
        $employee->delete();
        return back();
    }
    public function export()
    {
        return Excel::download(new EmployeeExport, 'Employee.xlsx');
    }
    public function exportPDF()
    {
        $employees = Employee::all();
        $pdf = PDF::loadView('pdf.employees', ['employees' => $employees]);
        return $pdf->download('employee.pdf');
    }
}

tugas_4/resources/views/company/create.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Tambah Employee</title>
</head>

<body>
    <div class="container">
        <div class="jumbotron mt-4">
            <h1 class="display-4">Hello, world!</h1>
            <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
            <hr class="my-4">
            <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
            <p class="lead">
                <a class="btn btn-primary " href="{{route('company.index')}}" role="button">Kembali</a>
            </p>
            <div class="bg-light  px-2 py-4">
                <form action="{{route('company.store')}}" method="POST">
                    {{csrf_field()}}
                    <div class="form-group row">
                        <label for="inputNama" class="col-sm-2 col-form-label">Nama</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="inputNama" placeholder="Nama" name="nama">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="inputNama" class="col-sm-2 col-form-label">Alamat</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="inputNama" placeholder="Alamat" name="alamat">
                        </div>
                    </div>
                    <button type="submit" class="btn btn-warning btn-block">Tambah</button>
                </form>
            </div>
        </div>
    </div>



    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

tugas_4/resources/views/company/edit.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Edit</title>
</head>

<body>
    <div class="container">
        <div class="jumbotron mt-4">
            <h1 class="display-4">Hello, world!</h1>
            <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
            <hr class="my-4">
            <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
            <p class="lead">
                <a class="btn btn-primary " href="{{route('company.index')}}" role="button">Kembali</a>
            </p>
            <div class="bg-light  px-2 py-4">
                <form action="{{route('company.update',$company->id)}}" method="POST">
                    {{csrf_field()}}
                    {{method_field('PUT')}}
                    <div class="form-group row">
                        <label for="inputNama" class="col-sm-2 col-form-label">Nama</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="inputNama" value="{{$company->nama}}" name="nama">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="inputNama" class="col-sm-2 col-form-label">Alamat</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="inputNama" value="{{$company->alamat}}" name="alamat">
                        </div>
                    </div>
                    <button type="submit" class="btn btn-warning btn-block">Edit</button>
                </form>
            </div>
        </div>
    </div>



    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

tugas_4/resources/views/company/index.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <title>Company</title>
</head>

<body>
  <div class="container">
    <div class="jumbotron mt-4">
    <div class="d-flex justify-content-between">
        <h1 class="display-4">Manage Company</h1>
        <a href="/" class="btn btn-primary my-4">Kembali</a>
      </div>
      <hr class="my-4">
      <p class="lead">
        <a class="btn btn-primary " href="{{route('company.create')}}" role="button">Tambah</a>
        <a class="btn btn-warning " href="company-export" role="button">Export</a>
        <a class="btn btn-warning " href="company-exportPDF" role="button">Export</a>

      </p>
      <div class="bg-light">
        <table class="table table-striped">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Nama</th>
              <th scope="col">Alamat</th>
              <th scope="col">Aksi</th>
            </tr>
          </thead>
          <tbody>
            <?php
            $no = 0 ?>
            @foreach($companies as $company)
            <?php
            $no++; ?>
            <tr>
              <th scope="row">{{$no}}</th>
              <td>{{$company->nama}}</td>
              <td>{{$company->alamat}}</td>
              <td>
                <a href="{{route('company.edit',$company->id)}}" class="btn btn-info">Edit</a>
                <a href="#{{$company->id}}-hapus" class="btn btn-danger" data-toggle="modal">Hapus</a>
              </td>
            </tr>
            @endforeach

          </tbody>
        </table>
      </div>
    </div>
  </div>
  <!-- Hapus -->
  @foreach($companies as $p)
  <div class="modal fade" id="{{$p->id}}-hapus">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        </div>
        <div class="modal-body">
          <h5 class="modal-title text-center">Hapus {{$p->nama}}</h5>
          <form action="{{route('company.destroy',$p->id)}}" method="post" role="form">
            {{csrf_field()}}
            {{method_field('DELETE')}}
            <input type="submit" name="nama" value="Hapus" class="btn btn-danger btn-block">
          </form>
        </div>
      </div>
    </div>
  </div>
  @endforeach

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

tugas_4/resources/views/employees/create.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Tambah Employee</title>
</head>

<body>
    <div class="container">
        <div class="jumbotron mt-4">
            <h1 class="display-4">Hello, world!</h1>
            <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
            <hr class="my-4">
            <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
            <p class="lead">
                <a class="btn btn-primary " href="{{route('employee.index')}}" role="button">Kembali</a>
            </p>
            <div class="bg-light  px-2 py-4">
                <form action="{{route('employee.store')}}" method="POST">
                    {{csrf_field()}}
                    <div class="form-group row">
                        <label for="inputNama" class="col-sm-2 col-form-label">Nama</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="inputNama" placeholder="Nama" name="nama">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="inputNama" class="col-sm-2 col-form-label">Atasan Id</label>
                        <div class="col-sm-10">
                            <select class="form-control" name="atasan_id" id="exampleFormControlSelect1">
                                <option value="1">Pilih Atasan</option>
                                @foreach($employees as $e)
                                    <option value="{{$e->id}}">{{$e->nama}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="inputNama" class="col-sm-2 col-form-label">Company</label>
                        <div class="col-sm-10">
                            <select name="company_id" class="form-control" id="exampleFormControlSelect1">
                            <option value="" >Pilih Company</option>
                            @foreach($companies as $company)
                                <option value="{{$company->id}}">{{$company->nama}}</option>
                            @endforeach
                            </select>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-warning btn-block">Tambah</button>
                </form>
            </div>
        </div>
    </div>



    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

tugas_4/resources/views/employees/edit.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Tambah Employee</title>
</head>

<body>
    <div class="container">
        <div class="jumbotron mt-4">
            <h1 class="display-4">Hello, world!</h1>
            <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
            <hr class="my-4">
            <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
            <p class="lead">
                <a class="btn btn-primary " href="{{route('employee.index')}}" role="button">Kembali</a>
            </p>
            <div class="bg-light  px-2 py-4">
                <form action="{{route('employee.update',$employee->id)}}" method="POST">
                    {{csrf_field()}}
                    {{method_field('PUT')}}
                    <div class="form-group row">
                        <label for="inputNama" class="col-sm-2 col-form-label">Nama</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="inputNama" placeholder="Nama" name="nama" value="{{$employee->nama}}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="inputNama" class="col-sm-2 col-form-label">Atasan Id</label>
                        <div class="col-sm-10">
                            <select class="form-control" name="atasan_id" id="exampleFormControlSelect1">
                                @foreach($employees as $e)
                                <option value="{{$e->id}}" 
                                    <?php
                                        if ($e->id == $employee->atasan_id) {
                                            echo "selected";
                                        }
                                    ?>
                                >{{$e->nama}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="inputNama" class="col-sm-2 col-form-label">Company</label>
                        <div class="col-sm-10">
                            <select name="company_id" class="form-control" id="exampleFormControlSelect1">

                                @foreach($companies as $company)
                                <option value="{{$company->id}}" 
                                    <?php
                                        if ($employee->company_id == $company->id) {
                                            echo "selected";
                                        }
                                    ?>
                                >{{$company->nama}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-warning btn-block">Edit</button>
                </form>
            </div>
        </div>
    </div>



    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

tugas_4/resources/views/employees/index.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <title>Employee</title>
</head>

<body>
  <div class="container">
    <div class="jumbotron mt-4">
      <div class="d-flex justify-content-between">
        <h1 class="display-4">Manage Employee</h1>
        <a href="/" class="btn btn-primary my-4">Kembali</a>
      </div>
      <hr class="my-4">
      <p class="lead">
        <a class="btn btn-primary " href="{{route('employee.create')}}" role="button">Tambah</a>
        <a class="btn btn-warning " href="employee-export" role="button">Export Excel</a>
        <a class="btn btn-warning " href="employee-exportPDF" role="button">Export PDF</a>
      </p>
      <div class="bg-light">
        <table class="table table-striped">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Nama</th>
              <th scope="col">Jabatan</th>
              <th scope="col">Nama Atasan</th>
              <th scope="col">Perusahaan</th>
              <th scope="col">Aksi</th>
            </tr>
          </thead>
          <tbody>
            <?php
            $no = 0 ?>
            @foreach($employees as $e)
            <?php
            $no++; ?>
            <tr>
              <th scope="row">{{$no}}</th>
              <td>{{$e->nama}}</td>
              <td>
                @if($e->atasan_id =='')
                <p>CEO</p>
                @elseif($e->atasan_id ==1)
                <p>Direksi</p>
                @elseif($e->id ==4 || $e->id ==5 )
                <p>Manager</p>
                @else
                <p>staff</p>

                @endif

              </td>
              <td>
                @if($e->atasan_id =='')
                <p>Owner</p>
                @else
                @foreach($employees as $employee)
                @if($employee->id == $e->atasan_id)
                <p>{{$employee->nama}}</p>
                @endif
                @endforeach
                @endif
              </td>
              <td>
                @foreach($companies as $company)
                @if($company->id == $e->company_id)
                <p>{{$company->nama}}</p>

                @endif
                @endforeach
              </td>
              <td>
                <a href="{{route('employee.edit',$e->id)}}" class="btn btn-info">Edit</a>
                <a href="#{{$e->id}}-hapus" class="btn btn-danger" data-toggle="modal">Hapus</a>
              </td>
            </tr>
            @endforeach

          </tbody>
        </table>
      </div>
    </div>
  </div>
  <!-- Hapus -->
  @foreach($employees as $p)
  <div class="modal fade" id="{{$p->id}}-hapus">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        </div>
        <div class="modal-body">
          <h5 class="modal-title text-center">Hapus {{$p->nama}}</h5>
          <form action="{{route('employee.destroy',$p->id)}}" method="post" role="form">
            {{csrf_field()}}
            {{method_field('DELETE')}}
            <input type="submit" name="nama" value="Hapus" class="btn btn-danger btn-block">
          </form>
        </div>
      </div>
    </div>
  </div>
  @endforeach

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

tugas_4/resources/views/pdf/companies.blade.php
<table class="table" border="1">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nama</th>
            <th scope="col">Alamat</th>
        </tr>
    </thead>
    <tbody>
    <?php
            $no = 0 ?>
        @foreach($companies as $company)
        <?php
            $no ++ ?>
            <tr>
                <th scope="row">{{$no}}</th>
                <td>{{$company->nama}}</td>
                <td>{{$company->alamat}}</td>
            </tr>
        @endforeach
    </tbody>
</table>

tugas_4/resources/views/pdf/employees.blade.php
<table class="table" border="1">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nama</th>
            <th scope="col">Atasan Id</th>
            <th scope="col">Company Id</th>
        </tr>
    </thead>
    <tbody>
    <?php
            $no = 0 ?>
        @foreach($employees as $employee)
        <?php
            $no ++ ?>
            <tr>
                <th scope="row">{{$no}}</th>
                <td>{{$employee->nama}}</td>
                <td>{{$employee->atasan_id}}</td>
                <td>{{$employee->company_id}}</td>
            </tr>
        @endforeach
    </tbody>
</table>